### PR TITLE
Adds bindings for DistrictAdmin and SchoolAdmin.

### PR DESCRIPTION
**Pull request by antinescience**
APIs for DistrictAdmin and SchoolAdmin exist, but bindings in the Python lib don't. I've added these and tested locally with our application.

### CODE REVIEW

**Comment by Christopher-Bradshaw** [comment]
Hi @antinescience thanks for the commit. If you could bump the version (I think this would be a minor change http://semver.org/) and add a note to the changelog I will merge this.

**Comment by antinescience** [comment]
@Christopher-Bradshaw all set.

**Comment by Christopher-Bradshaw** [comment]
Awesome, thanks!

**Comment by antinescience** [comment]
Hey @Christopher-Bradshaw - can you push this to PyPi? https://pypi.python.org/pypi/clever/ 2.1.1 still showing up as the most current version. Thanks!

**Comment by Christopher-Bradshaw** [comment]
@antinescience Sorry about that. Should be there now.

**Pull request merged**
